language: csharp
branches:
  only:
  - dev
dist: trusty
mono: none
os:
- linux
- osx
addons:
  apt:
    packages:
    - libunwind8
script:
- "./build.sh --ci /p:BuildNumber=$((10000+TRAVIS_BUILD_NUMBER))"
- nuget pack ./artifacts/build/*.nupkg
- nuget push ./artifacts/build/*.nupkg -ApiKey $API_KEY -Source $NUGET_SOURCE
env:
  global:
  - secure: pQP7BWiWG8MWnpaBnMMIeNfrunJKzs6R+vXKGU/mBZVRgQ1T022bcjBKb3kCu+OUDvxueNGKyRYauC15NVVRx4SuzWZM/Rpac/UJjfF/5ptFzuilcyKrGgZnVpVTmX9Xifie3Jh5JHMoBG8NhCO1W4/OARlcTaaUIN6QnNLNLA0PYX955zIzGsGA5sTV7KsjxvbYY2gdL2qTUqVe6O4vM/tm3es/etdbHUbQcqFBXHfJWKTK1BbX4BTNH9s3BFNzabQIUGTHOAARQL+iB+SPg9CQ7c+W2pyQXbF1buRwAwf0lsVmpPOorypSHZYZtcd/kSohQ7AXaMfOm2+1hwoLGRYl5B7PwQFlem52UEC9LiUgFVUrY1PUthbQ2vOIr0Rk37cJsiciD3lbSSZp4fRn7YS/iD7uUh+dL2tUpMi/lYyLQ3IuMQW6RHwGiG7qBPkXY+s1eGLSr690dnugNavGQL44Wn+BsNp1w2xkdgErpyHHE/lr5CFjSb3nH5CjuYfmUM6ppyb5oafaqlTfzahIXJzl3tcmn011333OBFGcgV7FS6FcZe/PLGgdcD7yQ0x4MW2o2Wvd7C7DceA5cUAEB/H2pGgaaj6RkA3aXX2Gx1W1IrYFcquJmSo0pdTtAGi0YmSGvPKa/YbfxPAKANssTKc1/93k8tsFCpdxCYlCe6c=
  - secure: LpQImLhoCNI57nU1AHVz+W0BIeQ0sD1O6nzRvxkYnu5rx23RoxGGC/2vtcQsc1biwWVxZKem/W0OprBgtKXTLb7Y1jAaooH4Up5vdSM0Qjofjfdwan+qayaDTSbjFk95bmwJhsdx8vB0dQ5vpZwsFNi5V161fYznCel7TlcKdVjPyQ0SdKF69S0uIgO3r7fXOvB8sLNQES4TNNdDBboZIonHx9Xe0G8B6oPeqZalDKNGaf+WAeNHVcjBdYltFFuDFkRshuRrgSQMfaaegwSyzEDZeCQnXBQdTUvpZ0m++1WaZuQ26+WUGORG+YKFXdjK8hIsgK3tZQAx6aB2Mg7JfcE3fI5jiKlswj15Fes0zQSGFKG0mKNs85ud9Y6FlbPRKa+QwICmZKN0pIZFowd3MEtYAo0X+7D4GRYg7Z2zpWUoCBdAPYDLxHTnawhtPA6rY4zFQt18kSqXTva7mKgGloqQbejs2YFQ/M5rPtenaz0p6JsM1Bleq/ebPR4Oxntjm4Lcs/DP2ffrh6lPm4avkaZFv+333RIXbFFnUGi+T8OrHWxH01yZrmw+C9toLMEPWQy6J3V/xdmChheW+9Jn18kGVWW5aQ2DPo2Oti/BX9fIopO9KkFq1PHfKbT0d1UTnHgj2oXfzPwDiq+fXChCqAZdSsM7IWBLT37f2aaRooA=
